/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_first_testndkhelloworld_HelloJni */

#ifndef _Included_com_first_testndkhelloworld_HelloJni
#define _Included_com_first_testndkhelloworld_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_first_testndkhelloworld_HelloJni
 * Method:    sayHello
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_first_testndkhelloworld_HelloJni_sayHello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
